#!/bin/bash

rm -rf Pods/RxSwift
rm -rf Pods/RxCocoa
rm -rf Pods/AFNetworking
rm -rf Pods/AMap3DMap
rm -rf Pods/AMapFoundation
rm -rf Pods/AMapLocation
rm -rf Pods/APM
rm -rf Pods/AipBase
rm -rf Pods/Alamofire
rm -rf Pods/AlgoLib
rm -rf Pods/Charts
rm -rf Pods/CleanJSON
rm -rf Pods/DDWebService
rm -rf Pods/CryptoSwift
rm -rf Pods/FSCalendar
rm -rf Pods/FPSMonitor
rm -rf Pods/FSPagerView
rm -rf Pods/FirebaseCore
rm -rf Pods/FirebaseABTesting
rm -rf Pods/FirebaseCore
rm -rf Pods/FirebaseCrashlytics
rm -rf Pods/FirebaseInstallations
rm -rf Pods/FirebasePerformance
rm -rf Pods/FirebaseRemoteConfig
rm -rf Pods/GBDeviceInfo
rm -rf Pods/GCDWebServer
rm -rf Pods/GDataXML-HTML
rm -rf Pods/GTMSessionFetcher
rm -rf Pods/GTMAppAuth
rm -rf Pods/GoogleAppMeasurement
rm -rf Pods/GoogleDataTransport
rm -rf Pods/GoogleSignIn
rm -rf Pods/GoogleUtilities
rm -rf Pods/LineSDK
rm -rf Pods/Logan
rm -rf Pods/MIBrain
rm -rf Pods/MMKV
rm -rf Pods/MMKVCore
rm -rf Pods/MagicalRecord
rm -rf Pods/Moya
rm -rf Pods/Parchment
rm -rf Pods/PromisesObjC
rm -rf Pods/Protobuf
rm -rf Pods/QuickLayout
rm -rf Pods/Reusable
rm -rf Pods/RxRelay
rm -rf Pods/SAMKeychain
rm -rf Pods/SDWebImage
rm -rf Pods/Selene
rm -rf Pods/SwiftEntryKit
rm -rf Pods/SwiftProtobuf
rm -rf Pods/SwiftVender
rm -rf Pods/Swinject
rm -rf Pods/SwipeCellKit
rm -rf Pods/TWTagLengthValue
rm -rf Pods/TensorFlowLiteC
rm -rf Pods/TrustKit
rm -rf Pods/WoodPeckeriOS
rm -rf Pods/WatchPaiLib
rm -rf Pods/YYModel
rm -rf Pods/eigen
rm -rf Pods/libwebp
rm -rf Pods/lottie-ios
rm -rf Pods/nanopb
rm -rf Pods/objc-geohash
rm -rf Pods/opus-ios